-- review_flags — "I looked at this, and here is what I decided."
--
-- Paste into the Supabase SQL Editor and Run. Safe to run more than once.
--
-- Why a table and not a column on albums. A flag is about an album AND a
-- particular complaint: the same record can be a plausible duplicate, share
-- its sleeve with another, and have a suspect year, and you can settle those
-- three on different days. A column holds one answer, so it would force the
-- three to overwrite each other. Some flags are not about an album at all --
-- a held-back rename names a row that may since have been renamed away, and a
-- shared sleeve is a property of the image, not of either record wearing it.
--
-- So: (kind, subject) is the identity, and album_id rides along when there IS
-- an album, purely so the flag dies with it.
create table if not exists public.review_flags (
  id       bigint generated by default as identity primary key,

  -- The section id from health.json: 'year-gap', 'shared-cover',
  -- 'near-duplicate', 'rename-review', 'no-root', 'no-cover', 'no-genres'.
  -- Deliberately not a check constraint -- sections come and go, and a flag
  -- left behind by a retired section is harmless, where a failing insert on
  -- a new one would not be.
  kind     text not null,

  -- The stable key within that kind. 'album:<id>' where a row is one album,
  -- 'cover:<url>' for a shared sleeve, 'rename:<artist>::<title>' for a
  -- suggestion. Never the artist and title on their own: renaming the album
  -- is frequently the fix, and the flag must survive it.
  subject  text not null,

  -- Cascade, so settling an album and later deleting it does not leave the
  -- flag behind to be counted forever.
  album_id bigint references public.albums(id) on delete cascade,

  --   dismissed — checked, nothing wrong, stop showing me
  --   revisit   — something IS wrong, I could not fix it now
  -- 'revisit' is the reason this is not just a hidden-ids list: it keeps the
  -- row on screen, pinned, instead of hiding it.
  state    text not null default 'dismissed'
           check (state in ('dismissed', 'revisit')),

  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- One verdict per complaint per subject. The app upserts on this, so changing
-- your mind updates the row rather than stacking a second one.
create unique index if not exists review_flags_subject_key
  on public.review_flags (kind, subject);

-- Postgres does not index a foreign key for you; without this, deleting an
-- album makes the cascade scan the whole table.
create index if not exists review_flags_album_idx on public.review_flags (album_id);

create or replace function public.touch_review_flag() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists review_flags_touch on public.review_flags;
create trigger review_flags_touch
  before update on public.review_flags
  for each row execute function public.touch_review_flag();

-- Same model as the rest of the schema: anyone may read, only the one signed-in
-- account may write.
alter table public.review_flags enable row level security;

drop policy if exists review_flags_read  on public.review_flags;
drop policy if exists review_flags_write on public.review_flags;

create policy review_flags_read on public.review_flags
  for select to anon, authenticated using (true);

create policy review_flags_write on public.review_flags
  for all to authenticated using (true) with check (true);
