// config.js — generated by scripts/write-config.mjs, but safe to edit by hand.
//
// Both values come from your Supabase dashboard:
//   Project Settings -> Data API -> Project URL, and the publishable API key.
//
// They are meant to be public; they sit in browser code on purpose. What
// actually stops strangers writing to your collection is Row Level Security
// (db/schema.sql) plus having sign-ups turned off, not hiding these strings.
window.IH_CONFIG = {
  SUPABASE_URL: "https://hlgslntaqfzkqrxylrof.supabase.co",
  SUPABASE_KEY: "sb_publishable_EvtfueZnRajhAzd8XUHlEQ_RK8s5u9o",
};
