-- Infinite Music Catalog — Supabase schema
-- Paste this whole file into the Supabase SQL Editor and hit Run. It is safe
-- to run more than once -- with one exception that matters: it drops and
-- recreates the security policies below in their OPEN form, so running it on
-- a database that public_hardening.sql has tightened quietly loosens it again.
-- If you ever re-run this, run public_hardening.sql straight after.
--
-- This built the database, and it is kept describing the whole of it: every
-- change since lives in db/migrations/ AND is folded in here, so a database
-- rebuilt from this file alone matches the live one. Re-running it does not
-- apply a change -- `create table if not exists` skips a table that exists.
--
-- Security model: anyone can READ, only a signed-in user can WRITE. There is
-- exactly one account (yours), and public sign-ups are turned off in the
-- Supabase dashboard, so "authenticated" and "you" mean the same thing. That
-- avoids hard-coding your user id anywhere in the browser code.

-- ── albums ──────────────────────────────────────────────────────────────────
create table if not exists public.albums (
  id         bigint generated by default as identity primary key,
  artist     text    not null,
  title      text    not null,
  year       int,
  -- NULL = never scored. Kept distinct from 100 on purpose: the sheet lumped
  -- them together, which diluted the real 100s down to unscored odds. 70 and
  -- up is the rotation. Below it the app writes one grade, Not Recommended,
  -- stored as 45: rated, and out of every roll. 50-65 are still accepted from
  -- a scale that was briefly offered; any score under 70 reads as Not
  -- Recommended. db/migrations/2026-09-21-low-scores.sql
  score      int     constraint albums_score_check
                     check (score in (45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100)),
  notes      text,
  cover_url  text,
  -- MusicBrainz release-group id: the album's stable identity. Artwork and
  -- genres are looked up by this rather than by searching the title again,
  -- which is what stopped covers landing on the wrong record.
  mbid       uuid,
  genres     text[] not null default '{}',
  -- Where the album came from: the original spreadsheet, or added in the app.
  source     text not null default 'sheet' check (source in ('sheet', 'app')),
  -- Set when you choose a cover yourself. The nightly enrichment leaves those
  -- alone; without this it would overwrite your choice every night.
  cover_locked boolean not null default false,
  -- The album's own page on Apple Music, so the listen button opens the record
  -- rather than a search. Locked like the cover: a link set by hand is never
  -- replaced. Added by db/migrations/2026-09-21-apple-music-links.sql.
  apple_music_url    text,
  apple_music_locked boolean not null default false,
  -- Deleting is a tombstone, not a removal. The row stays, flagged, and the
  -- app, the backup and the importer all skip it -- so an old albums.csv that
  -- still carries the album cannot bring it back, and Restore is one update.
  deleted_at timestamptz,
  scored_at  timestamptz,
  created_at timestamptz not null default now()
);

-- Stops the same album sneaking in twice, the way three of them did in the
-- sheet. It covers deleted rows too, so re-adding a deleted album is refused
-- rather than duplicated -- the app points you at Restore instead.
create unique index if not exists albums_artist_title_key
  on public.albums (lower(artist), lower(title));

-- The app's one unavoidable query is every live album in artist/title order,
-- so the index matches it exactly. (An index on (id) would have been wasted:
-- the primary key already has one.)
create index if not exists albums_live_idx
  on public.albums (artist, title) where deleted_at is null;
-- No index for "unrated": the app loads the collection once and filters in the
-- browser, so nothing queries on it, and an unused index only slows writes.
create index if not exists albums_genres_idx on public.albums using gin (genres);

-- ── rolls ───────────────────────────────────────────────────────────────────
-- Every spin of the randomizer: the one record of what it actually served.
-- Written, and so far never read back by the app. `outcome` has no control
-- that sets it and stays null.
create table if not exists public.rolls (
  id        bigint generated by default as identity primary key,
  album_id  bigint not null references public.albums(id) on delete cascade,
  mode      text   not null check (mode in ('weighted', 'unscored', 'uniform')),
  outcome   text          check (outcome in ('played', 'skipped')),
  rolled_at timestamptz not null default now()
);
create index if not exists rolls_recent_idx on public.rolls (rolled_at desc);
-- Postgres does not index a foreign key for you. Without this, deleting an
-- album makes the cascade scan and lock the whole table.
create index if not exists rolls_album_idx on public.rolls (album_id);

-- ── keep scored_at honest ───────────────────────────────────────────────────
create or replace function public.touch_scored_at() returns trigger
language plpgsql as $$
begin
  if new.score is distinct from old.score then
    new.scored_at := case when new.score is null then null else now() end;
  end if;
  return new;
end $$;

drop trigger if exists albums_touch_scored_at on public.albums;
create trigger albums_touch_scored_at
  before update on public.albums
  for each row execute function public.touch_scored_at();

-- ── row level security ──────────────────────────────────────────────────────
alter table public.albums enable row level security;
alter table public.rolls  enable row level security;

do $$
declare t text;
begin
  foreach t in array array['albums', 'rolls'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read',  t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);

    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_read', t);

    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      t || '_write', t);
  end loop;
end $$;

-- ── review_flags ────────────────────────────────────────────────────────────
-- Your verdicts on the Fix list. Added by
-- db/migrations/2026-09-20-review-flags.sql, which explains why it is a table
-- of its own rather than a column on albums; folded in here so this file still
-- builds the whole database.
create table if not exists public.review_flags (
  id         bigint generated by default as identity primary key,
  kind       text not null,          -- the health.json section id
  subject    text not null,          -- 'album:<id>', 'rename:<artist>::<title>', ...
  album_id   bigint references public.albums(id) on delete cascade,
  state      text not null default 'dismissed' check (state in ('dismissed', 'revisit')),
  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists review_flags_subject_key on public.review_flags (kind, subject);
create index if not exists review_flags_album_idx on public.review_flags (album_id);

create or replace function public.touch_review_flag() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

drop trigger if exists review_flags_touch on public.review_flags;
create trigger review_flags_touch
  before update on public.review_flags
  for each row execute function public.touch_review_flag();

-- The same starting rules as the tables above. public_hardening.sql then
-- narrows reads AND writes to your user id -- nothing a visitor sees needs it.
alter table public.review_flags enable row level security;
drop policy if exists review_flags_read  on public.review_flags;
drop policy if exists review_flags_write on public.review_flags;
create policy review_flags_read on public.review_flags
  for select to anon, authenticated using (true);
create policy review_flags_write on public.review_flags
  for all to authenticated using (true) with check (true);
