-- Infinite Hipster — Supabase schema
-- Paste this whole file into the Supabase SQL Editor and hit Run. It is safe
-- to run more than once.
--
-- Security model: anyone can READ, only a signed-in user can WRITE. There is
-- exactly one account (yours), and public sign-ups are turned off in the
-- Supabase dashboard, so "authenticated" and "you" mean the same thing. That
-- avoids hard-coding your user id anywhere in the browser code.

-- ── albums ──────────────────────────────────────────────────────────────────
create table if not exists public.albums (
  id         bigint generated by default as identity primary key,
  artist     text    not null,
  title      text    not null,
  year       int,
  -- NULL = never scored. Kept distinct from 100 on purpose: the sheet lumped
  -- them together, which diluted the real 100s down to unscored odds.
  score      int     check (score in (70, 75, 80, 85, 90, 95, 100)),
  notes      text,
  cover_url  text,
  -- MusicBrainz release-group id: the album's stable identity. Artwork and
  -- genres are looked up by this rather than by searching the title again,
  -- which is what stopped covers landing on the wrong record.
  mbid       uuid,
  genres     text[] not null default '{}',
  -- Where the album came from. Albums added in the app are not in the
  -- spreadsheet, and the nightly sheet import must not treat them as strays.
  source     text not null default 'sheet' check (source in ('sheet', 'app')),
  -- Set when you choose a cover yourself. The nightly enrichment leaves those
  -- alone; without this it would overwrite your choice every night.
  cover_locked boolean not null default false,
  -- Deleting is a tombstone, not a removal. The sheet is read-only to us, so a
  -- hard delete would simply be re-imported the next night. The row stays,
  -- flagged, and both the app and the importer skip it.
  deleted_at timestamptz,
  scored_at  timestamptz,
  created_at timestamptz not null default now()
);

-- Stops the same album sneaking in twice, the way three of them did in the sheet.
create unique index if not exists albums_artist_title_key
  on public.albums (lower(artist), lower(title));

-- The app's one unavoidable query is every live album in artist/title order,
-- so the index matches it exactly. (An index on (id) would have been wasted:
-- the primary key already has one.)
create index if not exists albums_live_idx
  on public.albums (artist, title) where deleted_at is null;
-- No index for "unrated": the app loads the collection once and filters in the
-- browser, so nothing queries on it, and an unused index only slows writes.
create index if not exists albums_genres_idx on public.albums using gin (genres);

-- ── rolls ───────────────────────────────────────────────────────────────────
-- Every spin of the randomizer, so you can see what it has been feeding you
-- and avoid repeats. `outcome` stays null until you say what happened.
create table if not exists public.rolls (
  id        bigint generated by default as identity primary key,
  album_id  bigint not null references public.albums(id) on delete cascade,
  mode      text   not null check (mode in ('weighted', 'unscored', 'uniform')),
  outcome   text          check (outcome in ('played', 'skipped')),
  rolled_at timestamptz not null default now()
);
create index if not exists rolls_recent_idx on public.rolls (rolled_at desc);
-- Postgres does not index a foreign key for you. Without this, deleting an
-- album makes the cascade scan and lock the whole table.
create index if not exists rolls_album_idx on public.rolls (album_id);

-- ── keep scored_at honest ───────────────────────────────────────────────────
create or replace function public.touch_scored_at() returns trigger
language plpgsql as $$
begin
  if new.score is distinct from old.score then
    new.scored_at := case when new.score is null then null else now() end;
  end if;
  return new;
end $$;

drop trigger if exists albums_touch_scored_at on public.albums;
create trigger albums_touch_scored_at
  before update on public.albums
  for each row execute function public.touch_scored_at();

-- ── row level security ──────────────────────────────────────────────────────
alter table public.albums enable row level security;
alter table public.rolls  enable row level security;

do $$
declare t text;
begin
  foreach t in array array['albums', 'rolls'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read',  t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);

    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_read', t);

    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      t || '_write', t);
  end loop;
end $$;
