-- Infinite Hipster — Supabase schema
-- Paste this whole file into the Supabase SQL Editor and hit Run. It is safe
-- to run more than once.
--
-- Security model: anyone can READ, only a signed-in user can WRITE. There is
-- exactly one account (yours), and public sign-ups are turned off in the
-- Supabase dashboard, so "authenticated" and "you" mean the same thing. That
-- avoids hard-coding your user id anywhere in the browser code.

-- ── albums ──────────────────────────────────────────────────────────────────
create table if not exists public.albums (
  id         bigint generated by default as identity primary key,
  artist     text    not null,
  title      text    not null,
  year       int,
  -- NULL = never scored. Kept distinct from 100 on purpose: the sheet lumped
  -- them together, which diluted the real 100s down to unscored odds.
  score      int     check (score in (70, 75, 80, 85, 90, 95, 100)),
  in_pool    boolean not null default true,   -- the sheet's RSP column
  notes      text,
  cover_url  text,
  -- MusicBrainz release-group id: the album's stable identity. Artwork and
  -- genres are looked up by this rather than by searching the title again,
  -- which is what stopped covers landing on the wrong record.
  mbid       uuid,
  genres     text[] not null default '{}',
  scored_at  timestamptz,
  created_at timestamptz not null default now()
);

-- Stops the same album sneaking in twice, the way three of them did in the sheet.
create unique index if not exists albums_artist_title_key
  on public.albums (lower(artist), lower(title));

create index if not exists albums_pool_idx on public.albums (in_pool) where in_pool;
create index if not exists albums_unscored_idx on public.albums (id) where score is null;
create index if not exists albums_genres_idx on public.albums using gin (genres);

-- ── rolls ───────────────────────────────────────────────────────────────────
-- Every spin of the randomizer, so you can see what it has been feeding you
-- and avoid repeats. `outcome` stays null until you say what happened.
create table if not exists public.rolls (
  id        bigint generated by default as identity primary key,
  album_id  bigint not null references public.albums(id) on delete cascade,
  mode      text   not null check (mode in ('weighted', 'unscored', 'uniform')),
  outcome   text          check (outcome in ('played', 'skipped')),
  rolled_at timestamptz not null default now()
);
create index if not exists rolls_recent_idx on public.rolls (rolled_at desc);

-- ── plays ───────────────────────────────────────────────────────────────────
-- A listening log. Separate from rolls because you also play albums you went
-- looking for yourself.
create table if not exists public.plays (
  id        bigint generated by default as identity primary key,
  album_id  bigint not null references public.albums(id) on delete cascade,
  played_at timestamptz not null default now(),
  source    text not null default 'manual' check (source in ('roll', 'manual'))
);
create index if not exists plays_recent_idx on public.plays (played_at desc);

-- ── keep scored_at honest ───────────────────────────────────────────────────
create or replace function public.touch_scored_at() returns trigger
language plpgsql as $$
begin
  if new.score is distinct from old.score then
    new.scored_at := case when new.score is null then null else now() end;
  end if;
  return new;
end $$;

drop trigger if exists albums_touch_scored_at on public.albums;
create trigger albums_touch_scored_at
  before update on public.albums
  for each row execute function public.touch_scored_at();

-- ── row level security ──────────────────────────────────────────────────────
alter table public.albums enable row level security;
alter table public.rolls  enable row level security;
alter table public.plays  enable row level security;

do $$
declare t text;
begin
  foreach t in array array['albums', 'rolls', 'plays'] loop
    execute format('drop policy if exists %I on public.%I', t || '_read',  t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);

    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_read', t);

    execute format(
      'create policy %I on public.%I for all to authenticated using (true) with check (true)',
      t || '_write', t);
  end loop;
end $$;
