// write-config.mjs — generate app/config.js from the environment.
//
//   set -a && source .env && set +a && node scripts/write-config.mjs
//
// Only reads SUPABASE_URL and SUPABASE_KEY. Both are meant to be public --
// they ship inside browser code — so this file is committed like any other.
// What stops strangers writing to the collection is Row Level Security and
// sign-ups being off, not keeping these two strings secret. The password in
// your .env is never read here and never reaches the repo.

import { writeFileSync } from "node:fs";

const { SUPABASE_URL, SUPABASE_KEY } = process.env;
const missing = ["SUPABASE_URL", "SUPABASE_KEY"].filter((k) => !process.env[k]);
if (missing.length) {
  console.error(`Missing ${missing.join(" and ")}.`);
  console.error(`Try:  set -a && source .env && set +a && node scripts/write-config.mjs`);
  process.exit(1);
}

if (!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/.test(SUPABASE_URL)) {
  console.error(`SUPABASE_URL does not look like a project URL: ${SUPABASE_URL}`);
  console.error(`Expected something like https://abcdefghijkl.supabase.co`);
  process.exit(1);
}
// A secret key here would end up in browser code and in the public repo.
if (/^sb_secret|service_role/.test(SUPABASE_KEY)) {
  console.error("That is the SECRET key. Use the publishable one (sb_publishable_...).");
  console.error("The secret key bypasses Row Level Security and must never reach the browser.");
  process.exit(1);
}

const url = SUPABASE_URL.replace(/\/$/, "");
writeFileSync(new URL("../app/config.js", import.meta.url),
`// config.js — generated by scripts/write-config.mjs, but safe to edit by hand.
//
// Both values come from your Supabase dashboard:
//   Project Settings -> Data API -> Project URL, and the publishable API key.
//
// They are meant to be public; they sit in browser code on purpose. What
// actually stops strangers writing to your collection is Row Level Security
// (db/schema.sql) plus having sign-ups turned off, not hiding these strings.
window.IH_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(url)},
  SUPABASE_KEY: ${JSON.stringify(SUPABASE_KEY)},
};
`);

console.log(`app/config.js written`);
console.log(`  url: ${url}`);
console.log(`  key: ${SUPABASE_KEY.slice(0, 18)}…  (publishable, safe to commit)`);
console.log(`\nThe app switches out of LOCAL mode on the next hard reload.`);
